twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        settings: '%app.settings%'
        
when@test:
    twig:
        strict_variables: true